steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [ "build", "-t ${_USERNAME}/${_REPO_NAME}", "-f docker/ubuntu/Dockerfile", "." ]
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker login --username=${_USERNAME} --password=$$PASSWORD"]
    secretEnv: ["PASSWORD"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_USERNAME}/${_REPO_NAME}"]
images:
  - "${_USERNAME}/${_REPO_NAME}"
secrets:
  - kmsKeyName: projects/vpser-d4aae/locations/global/keyRings/default/cryptoKeys/default
    secretEnv:
      PASSWORD: CiQAFtIQkebU11h4FtOmmjr3zdx3676uu4gb1UwbhM6qeydq69sSNAAdbQI+ZzcgFAZpmUxLRBznVJ7e7sjCkstIuvgAu9jNrOOharaxi1pmohS0fgiwkWX4A+A=
substitutions:
  _USERNAME: limaofeng
  _REPO_NAME: ssmgr
